# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[directory]
truncation_length = 5
truncation_symbol = "â€¦/"
truncate_to_repo = false

[git_branch]
symbol = 'ğŸŒ± '

[nodejs]
symbol = "â˜•ï¸"

[username]
style_user = "bold dimmed blue"
show_always = false

[sudo]
disabled = false

# Disable these modules, they're noisy
[aws]
disabled = true

[package]
disabled = true
